### ISSUE TITLE
Wie lass ich die "Ausgabe" als Bild anzeigen...

### ISSUE THREAD

**Issue by KariyakiLP** [irgendwr/dsbmobile-php-api#1]
Wie lass ich die "Ausgabe" als Bild anzeigen. Ich bekomme es einfach nicht hin...

**Comment by irgendwr** [comment]
Kannst du mir die Zugangsdaten geben, damit ich mir das mal ansehen kann? (evtl. per email oder so)

`$url = getTopicChildUrl();` sollte wahrscheinlich die url zum Bild zurückgeben, die kannst du dann ganz  normal ausgeben, z.B. so:
`echo '<p style="text-align:center;"><img src="' . $url . '" /></p>';`

**Comment by KariyakiLP** [comment]
Ok Danke :D Dank der API hab ich nen Telegram Bot gemacht :D

**Comment by irgendwr** [comment]
Hm, wollte ich auch mal machen, hab ich aufgrund der Masse an anderen Projektideen und meiner Faulheit dann doch nicht gemacht ^^
Hab die dsb-api irgendwann mal reverse-engineered und fix ne lib zusammengebastelt und mich nach nem Jahr entschieden das auf Github zu packen, hätte nie gedacht, dass das einer nützlich finden würde xD

**Comment by KariyakiLP** [comment]
;)

**Comment by KariyakiLP** [comment]
Hättest du das nicht gemacht, würde meine Klasse immer jeden Tag fragen bla bla :D
.. Ich mach mir nen neuen Git Acc weil mein neuer Name VentrixCode ist..

**Comment by irgendwr** [comment]
kay, brauchst die issue nicht immer wieder öffnen 😛
