### ISSUE TITLE
Wie kann man Bilder und News abrufen?

### ISSUE THREAD

**Issue by ghost** [irgendwr/dsbmobile-php-api#5]
Ich bin dabei unserer Schule eine Art Dashboard zu programmieren. Ich würde gerne die Stundenpläne auch miteinbinden. Die Stundenpläne ist unter Aushänge als Bilder gespeichert. Ist es möglich mit deiner API diese auch abzurufen ? 
Also das wäre dann quasi Menupunkt 2 ("Aushänge")
Und dann zum Beispiel Stundenplan 15 ...

**Comment by irgendwr** [comment]
Ja, du bekommst von der Api die url vom Bild zurück, guck dir evtl. mal issue #1 an.

**Comment by irgendwr** [comment]
@HubbleJo ich nehme mal an ich kann die issue schließen? Wenn noch was unklar ist einfach nachfragen ^^

**Comment by HubbleJo** [comment]
Die habe ich gelesen. Jetzt hab ichs gecheckt :) 

Ich hätte aber noch eine Frage ...
Wie kann ich die News bekommen ? 
das wäre ja Topic 3 oder ? 
![unbenannt](https://cloud.githubusercontent.com/assets/25012482/23313400/d1e674b4-fabd-11e6-8603-d5e7ca5b152c.PNG)

**Comment by ghost** [comment]
Die habe ich gelesen. Jetzt hab ichs gecheckt :) 

Ich hätte aber noch eine Frage ...
Wie kann ich die News bekommen ? 
das wäre ja Topic 3 oder ? 
![unbenannt](https://cloud.githubusercontent.com/assets/25012482/23313400/d1e674b4-fabd-11e6-8603-d5e7ca5b152c.PNG)

**Comment by irgendwr** [comment]
ja, im code sollte das dann quasi das 2. topic sein (zero-based numbering und so... ^^)

**Comment by ghost** [comment]
Ich probiers mal :smile:

**Comment by ghost** [comment]
Ich habe es jetzt getestet. Aber ich bekomme nie eine URL zurück ... =(
Ich habe zwar schon eine andere Lösung gefunden, aber die ist nicht so elegant ...

**Comment by irgendwr** [comment]
Wenn du willst, kannst du mir die Zugangsdaten geben (Jonas@sandstorm-projects.de) und ich guck mir das mal an.

**Comment by ghost** [comment]
Also das mit den Bildern hab ich jetzt doch noch hinbekommen. Aber ich bekomme nur 2 Bilder (Bei 0 einen Stundenplan von einer Klasse, bei 1 den Ferienplan). Die News bekomme ih gar nicht.

**Comment by irgendwr** [comment]
Hi Jonas ^^, folgendes sollte für dich funktionieren:
```
<?php
include("dsb_api.php");

// get the data of the third topic
$news_data = DSB::getTopic(2, "USER", "PASSWORD");

// check for errors
if ($news_data === false) {
    echo "<center><h2>DSB Api Error</h2></center>";
} else {
    // loop through the news items
    foreach ($news_data->Root->Childs as $index => $news) {
        // display news item
        echo "<h2>" . ($index + 1) . ". News: </h2>\n";
        echo "Datum: $news->Date<br>\n";
        echo "Titel: $news->Title<br>\n";
        echo "Text: $news->Detail<br>\n";
    }
}
?>
```
Hm, ich könnte das vielleicht irgendwann ein bisschen einfacher machen an News zu kommen (und eine ordentliche Dokumentation wäre auch nicht schlecht), aber ich glaube so geht das auch erstmal 😄

**Comment by ghost** [comment]
Danke das hat funktioniert 😃

**Comment by ghost** [comment]
Ich dekomm die Api einfach nicht mehr zum laufen, seit dem ich mein Webserver aktualisiert habe ... :sob: 
Soll ich ne neue Issue machen ?

**Comment by irgendwr** [comment]
joa, wenn du meinst ^^
Hört sich aber nach nem Fehler von deiner Konfiguration an, hast wahrscheinlich vergessen die curl extention zu installieren oder so
Edit: guck auch mal bitte in den error log

**Comment by ghost** [comment]
Oh stimmt das hatte ich ganz vergessen :sweat_smile: ... Sorry :)

**Comment by ghost** [comment]
Ich habe curl jetzt nach installierrt aber es funktioniert leider immer noch nicht :(
Was für einen Error Log meinst du ?

**Comment by ghost** [comment]
vergiss es hab den Fehler gefunden ... Ich hab den Apache Service nicht neu gestartet ... mein Fehler
