### ISSUE TITLE
curl_init()

### ISSUE THREAD

**Issue by zeppelsoftware** [irgendwr/dsbmobile-php-api#8]
Hey, ever seen that?

`PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /dsb_api.php:91
Stack trace:d
#0 /dsb_api.php(142): DsbAccount->getData()
#1 /dsb_api.php(155): DsbAccount->getTopics()
#2 /bot.php(8): DsbAccount->getTopic(0)
#3 {main}
  thrown in /dsb_api.php on line 91
`

Some ideas?
Linux kernel. 
php7 and curl provided

**Comment by irgendwr** [comment]
You might be missing the curl module for PHP, on debian/ubuntu you should be able to install it with `sudo apt install php7.0-curl`.
